calls:
- max_evals: 10
  timeout: null
search:
  acq_func: UCB
  acq_optimizer: auto
  evaluator:
    num_workers: 1
    type: ThreadPoolEvaluator
  filter_duplicated: true
  filter_failures: mean
  initial_point_generator: random
  initial_points:
  - batch_size: 64
    conv_type: hgt
    dropout: 0.5
    hidden_channels: 128
    hidden_size: 128
    lr: 0.001
    num_conv_layers: 1
    num_heads: 2
    weight_decay: 0.0
  kappa: 1.96
  kwargs: {}
  log_dir: .
  max_failures: 100
  moo_scalarization_strategy: Chebyshev
  moo_scalarization_weight: null
  multi_point_strategy: cl_max
  n_initial_points: 10
  n_jobs: 1
  n_points: 10000
  objective_scaler: auto
  problem:
    conditions: []
    forbiddens: []
    hyperparameters:
    - default: 64
      name: batch_size
      sequence:
      - 16
      - 32
      - 64
      - 128
      - 256
      type: ordinal
    - choices:
      - hgt
      - han
      default: hgt
      name: conv_type
      type: categorical
      weights: null
    - default: 0.5
      name: dropout
      sequence:
      - 0.0
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      type: ordinal
    - default: 128
      name: hidden_channels
      sequence:
      - 16
      - 32
      - 64
      - 128
      - 256
      type: ordinal
    - default: 128
      name: hidden_size
      sequence:
      - 16
      - 32
      - 64
      - 128
      - 256
      type: ordinal
    - default: 0.001
      log: true
      lower: 1.0e-05
      name: lr
      type: uniform_float
      upper: 0.1
    - default: 1
      name: num_conv_layers
      sequence:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      type: ordinal
    - default: 2
      name: num_heads
      sequence:
      - 1
      - 2
      - 4
      - 8
      type: ordinal
    - default: 0.0
      name: weight_decay
      sequence:
      - 0.0
      - 1.0e-05
      - 5.0e-05
      - 0.0001
      type: ordinal
    json_format_version: 0.4
    python_module_version: 0.6.1
  random_state: null
  scheduler: null
  stopper: null
  surrogate_model: RF
  sync_communication: false
  type: CBO
  update_prior: false
  verbose: 0
  xi: 0.001
