name = "PowerModelsGMD"
uuid = "c92a0612-66bb-11e9-0491-518d0d864356"
authors = ["Arthur Barnes <abarnes@lanl.gov>, Adam Mate <amate@lanl.gov>"]
repo = "https://github.com/lanl-ansi/PowerModels.jl"
keywords = ["GMD", "E3 HEMP", "simulation", "evaluation", "mitigation", "optimalization"]
version = "0.4.0"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"

[compat]
julia = "^1"
Cbc = ">= 0.7"
InfrastructureModels = "~0.5.4"
Ipopt = ">= 0.6"
JSON = "~0.21"
JuMP = "~0.21"
Juniper = ">= 0.6"
MathOptInterface = ">= 0.9.19"
Memento = "~1.1"
PowerModels = "~0.17.4"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[targets]
test = ["Test", "Ipopt", "Cbc", "Juniper"]
